removed file extensions to allow node module style imports. closes #15
sergiodxa/grial pull request #18
Opened 2017-08-27 20:31 UTC by joernroeder

@see https://nodejs.org/api/modules.html#modules_all_together

2017-08-28 08:31 UTC, sergiodxa requested changes

2017-08-28 08:31 UTC, sergiodxa commented on server/index.js
> +const getModels = require('./app/models')
This changes are not required to support `./resolvers/index.js`

2017-08-28 14:10 UTC, joernroeder commented
@sergiodxa yes your're right – it was way to late yesterday. i removed the extensions in `/app` (and readded them in `index.js`) to allow node module loading for connectors, models and loaders as well.

2017-08-28 18:31 UTC, sergiodxa approved these changes

2017-08-28 18:32 UTC, merged

2017-10-03 21:16 UTC, joernroeder commented
@sergiodxa would you mind pushing a new version to npm? thx